lib/chef_apply/text.rb
If a pluralization exists in en.yml: 
```
plural_thing: !!pl 
1: one thing
n: many things 
```
But it's missing the "!!pl" qualifier, the following message is displayed when accessing `T.plural_thing(quantity_of_things)`: 
```
NoMethodError:
undefined method `to_sym' for 1:Integer
Did you mean?  to_s
```
The cause is not immediately apparent. This was because the TextWrapper dynamic method generation was receiving '1' and 'n' as keys, when they're internal to `r18n`. When the parent is correctly marked as `!!pl`, those values are not received as keys. 
With this change, we catch this condition and report it as follows: 
```
ChefApply::TextWrapper::MissingPlural:
i18n key status.converge.header.1 appears to reference a pluralization.
Please append the plural indicator '!!pl' to the end of …
```
=> Report i18n pluralizations that are not configured correctly

lib/chef_apply/ui/terminal.rb
Signed-off-by: Marc A. Paradise <marc.paradise@gmail.com>j
```
$ be chef-run ubuntu[1:2] user test1uu
[✔] Packaging cookbook... done!
[✔] Generating local policyfile... exporting... done!
┌ [✔] Converging targets...
├── [✔] [ubuntu1] Successfully converged target!
└── [✔] [ubuntu2] Successfully converged target!
```
After
```
$ be chef-run ubuntu[1:2] user test1uu
[✔] Generating local policyfile... exporting... done!
[✔] Converging targets...
├── [✔] [ubuntu1] Successfully converged target!
└── [✔] [ubuntu2] Successfully converged target!
```
=> Align converge multi-spinner with parent

README.md
The name wasn't right. No DCO required since this is in the readme.
=> Update the readme to remove some boilerplate

Vagrantfile
This makes running chef-apply across these temporary VMs easier with a
single "-i ~/.vagrant.d/insecure_private_key" switch.
Reduced some of the duplication of the 5 ubuntu entries to a loop.
- ~New functionality includes tests~ not applicable, really
=> use a common key for dev environment test VMs

lib/chef_apply/cli.rb
When I updated the local work (creating temp cookbook and policyfile
bundle) to use the job framework, I neglected to handle what happens
if the job fails. Exceptions would get thrown inside the job correctly
and the error reporter would print it, but that would not be visible to
the user since the job failure was not handled and the spinners would
overwrite the failure message. This fixes that to correctly raise an
error if there is a failed job.
Customer issue in slack
=> Handle single failed job when creating cookbook or policyfile

.expeditor/update_dep.sh
I think we originally copied this from the ChefDK, but the rake task we
were trying to invoke has never existed here.
N/A
=> Using correct task to update dependencies

.expeditor/config.yml, .expeditor/update_dep.sh, .github/CODEOWNERS, .github/ISSUE_TEMPLATE/SUPPORT_QUESTION.md
Fix failing chef version bumps in expeditor
Minor syncs from the other projects
=> Update expeditor and .github files

.expeditor/config.yml, .expeditor/verify.pipeline.yml, .github/CODEOWNERS, .github/ISSUE_TEMPLATE/SUPPORT_QUESTION.md, lib/chef_apply/log.rb, lib/chef_apply/startup.rb, spec/spec_helper.rb, spec/unit/log_spec.rb, spec/unit/startup_spec.rb
=> Test on windows in buildkite + update codeownerrs

Gemfile
You can't eval with dependabot
=> Simplify the Gemfile so we can use Dependabot

Vagrantfile
Changes the windows vm in Vagrantfile to tas50/win_2016, because that one works.
=> Update the windows VM to one that works

lib/chef_apply/action/base.rb, lib/chef_apply/action/converge_target.rb, lib/chef_apply/action/converge_target/ccr_failure_mapper.rb, lib/chef_apply/action/generate_local_policy.rb, lib/chef_apply/action/generate_temp_cookbook.rb, lib/chef_apply/action/generate_temp_cookbook/recipe_lookup.rb, lib/chef_apply/action/generate_temp_cookbook/temp_cookbook.rb, lib/chef_apply/action/install_chef.rb, lib/chef_apply/action/install_chef/minimum_chef_version.rb, lib/chef_apply/cli.rb, lib/chef_apply/cli/help.rb, lib/chef_apply/cli/options.rb, lib/chef_apply/cli/validation.rb, lib/chef_apply/config.rb, lib/chef_apply/file_fetcher.rb, lib/chef_apply/startup.rb, lib/chef_apply/target_host.rb, lib/chef_apply/target_resolver.rb, lib/chef_apply/telemeter.rb, lib/chef_apply/text.rb, lib/chef_apply/ui/error_printer.rb, lib/chef_apply/ui/plain_text_header.rb, lib/chef_apply/ui/terminal.rb
These are faster as they don't have to traverse the filesystem
=> Use require_relative instead of require

chef-apply.gemspec, i18n/errors/en.yml, lib/chef_apply/action/generate_temp_cookbook/recipe_lookup.rb, lib/chef_apply/action/generate_temp_cookbook/temp_cookbook.rb, spec/unit/action/generate_temp_cookbook/recipe_lookup_spec.rb, spec/unit/action/generate_temp_cookbook/temp_cookbook_spec.rb
UX for users should not change:
```
chef-run hostname /path/to/recipe.yml
chef-run hostname cookbook_name::recipe_name
```
Minor version bump because we are depending on the latest version of Chef Infra Client
=> Adding YAML recipe support

.expeditor/run_linux_tests.sh, .expeditor/verify.pipeline.yml, Gemfile, chef-apply.gemspec, spec/spec_helper.rb, spec/unit/action/converge_target_spec.rb
Test on what we support and get the build green again
=> Fix chefstyle failures & require Ruby 2.6 since we need Chef 16 which is 2.6+

i18n/en.yml, i18n/errors/en.yml
=> Fix URLs that had not yet been updated to docs.chef.io

i18n/en.yml, spec/integration/fixtures/chef_help.out
Signed-off-by: Nikhil Gupta <nikhilgupta2102@gmail.com>
Added a more information to provide an explanation that the required format is cookbook name::recipename
[https://github.com/chef/chef-workstation/issues/168](url)
=> Updated the format for help text

Gemfile, Rakefile
=> Remove unused yard deps and rake task

CODE_OF_CONDUCT.md, CONTRIBUTING.md
Make sure we have all the docs we need
=> Add code of conduct and contributing docs

i18n/errors/en.yml
=> Fix typo in error message flag

CODEOWNERS
=> Remove the duplicate codeowners file

.github/lock.yml
=> Remove the github issue lock configuration

i18n/en.yml
This is a massive wall of text we throw at people. Simplify what we say
and link them to our docs for more information
=> Shorten the description of Telemetry

.expeditor/verify.pipeline.yml, chef-apply.gemspec
Support N-1 ruby for this tool as we are the consumers within
workstation.
=> Require Ruby 2.7 or later

.expeditor/verify.pipeline.yml
=> Switch windows tests to Ruby 2.7 docker image

.gitignore, dev-doc/README.md
Signed-off-by: Pranay Singh <i5singh.pranay@gmail.com>
Documentation for basic setup for devs in local system
=> Adding dev documentation

.expeditor/verify.pipeline.yml, .github/workflows/lint.yaml, .gitignore
Tests on this repo were blowing up
=> Disable yml and md linting and fix chefstyle

cspell.json, dev-doc/README.md, lib/chef_apply/action/base.rb, lib/chef_apply/action/converge_target.rb, lib/chef_apply/action/generate_temp_cookbook/temp_cookbook.rb, lib/chef_apply/cli.rb, lib/chef_apply/cli/options.rb, lib/chef_apply/startup.rb, lib/chef_apply/target_host.rb, lib/chef_apply/target_resolver.rb, lib/chef_apply/text.rb, spec/unit/startup_spec.rb, spec/unit/target_resolver_spec.rb
=> Add cspell config to fix spellcheck failures

lib/chef_apply/action/install_chef/minimum_chef_version.rb
Fixes, failing issue of aix, while running 'aix' as a supported target operating system.
related - https://github.com/chef/chef-apply/pull/201
=> adding a fix for failing aix

.expeditor/run_windows_tests.ps1, .expeditor/verify.pipeline.yml, Rakefile, spec/unit/cli_spec.rb
Signed-off-by: nikhil2611 <nikhilgupta2102@gmail.com>
Added ruby 3.0/3.1 windows and linux image to run test cases
=> Added ruby 3.0/3.1 windows/linux image

dev-doc/README.md
=> Minor change in Readme
