chef/chef-apply

chef-apply.gemspec
This should fix our
```
$ gem push chef-apply-0.1.1.gem --host http://***:8081/api/gems/omnibus-gems-local --key *** 2>&1
ERROR:  While executing gem ... (URI::InvalidURIError)
bad URI(is not URI?): TODO: Set to 'http://mygemserver.com'
```
error from Expeditor
=> We need to push to our private Gem repo

lib/chef_apply/action/install_chef/base.rb
This is a bug I accidently committed when doing the move to this repo
Signed-off-by: tyler-ball <tball@chef.io>
=> Raise error if installed Chef version is lower than 14.1.1

lib/chef_apply/cli.rb, lib/chef_apply/startup.rb, lib/chef_apply/ui/terminal.rb, spec/unit/cli_spec.rb, spec/unit/startup_spec.rb
Rather than have some logging set up in Startup::setup_logging
and some in CLI::configure_chef, this puts both into setup_logging
This also adds setup of  error handling for threads to Startup.
=> Move chef logging configuration to Startup

lib/chef_apply/action/base.rb, spec/unit/action/base_spec.rb
Different version of Chef (13/14) all behave differently on different
OSes (*nix, Windows) when it comes to specifying the `chef-client
--config` option. See the comment in this change for details.
Chef throws the following error on *nix:
```
sudo chef-client -z --config workstation.rb --recipe-url cw_directory_policy-03eb35d4ce71236f6ccd809d1feec5412eaa22e9ed79bcda34e4c04a7e4faf76.tgz
Starting Chef Client, version 13.10.0
resolving cookbooks for run list: []
Synchronizing Cookbooks:
Installing Cookbook Gems:
Compiling Cookbooks...
[2018-07-13T22:08:38+00:00] WARN: Node ubuntu1 has an empty run list.
Converging 0 resources
Running handlers:
- ChefApply::Reporter
Running handlers complete
Chef Client finished, 0/0 resources updated in 01 seconds
[2018-07-13T22:08:38+00:00] WARN: …
```
=> [SHACK-295] Chef 13 on Linux requires absolute paths for config location

i18n/en.yml, lib/chef_apply/action/generate_local_policy.rb, lib/chef_apply/action/generate_temp_cookbook.rb, lib/chef_apply/cli.rb, lib/chef_apply/cli/validation.rb, lib/chef_apply/error.rb, lib/chef_apply/temp_cookbook.rb, spec/unit/action/generate_local_policy_spec.rb, spec/unit/action/generate_temp_cookbook_spec.rb, spec/unit/cli/validation_spec.rb, spec/unit/cli_spec.rb, spec/unit/temp_cookbook_spec.rb
For review after #12 merges. 
In order to keep the UI logic separate from functional behaviors,
this change moves generation and export of cookbook+policy out of
'cli.rb' and into two new actions GenerateTempCookbook and
GenerateLocalPolicy.
It updates the usage to follow the patterns used for other actions
pulled in by ChefApply::CLI.
=> [SHACK-187] Move cookbook creation to actions

lib/chef_apply/cli.rb, lib/chef_apply/error.rb, lib/chef_apply/errors/standard_error_resolver.rb, lib/chef_apply/text.rb, lib/chef_apply/text/text_wrapper.rb, lib/chef_apply/ui/error_printer.rb, spec/unit/ui/error_printer_spec.rb
Overdue minor housekeeping that splits out the TextWrapper and StandardErrorMapper classes into their own files. This also updates `Text` to be a module instead of a class. 
Once #15 merges, errors/en.yml will no longer show as a new file.
=> [SHACK-187] housekeeping:  move text and error classes into their own files

i18n/errors/en.yml, lib/chef_apply/action/install_chef/base.rb, lib/chef_apply/cli/options.rb, spec/unit/action/install_chef/base_spec.rb
For users with an existing Chef Client 13 at version 13.10 or greater we
should not fail out. This version of Chef Client has the necessary fixes
to execute the chef-run policyfile bundle successfully.
SHACK-290
Signed-off-by: tyler-ball <tball@chef.io>
=> [SHACK-290] Support installed version of Chef 13 if 13.10 or greater

.expeditor/config.yml, chef-apply.gemspec, warning.txt
This is the first PR needed for SHACK-304. Promoting the `chef-apply` gem on every PR merge means that all we need to do in ChefDK is update dependencies to get the latest set of changes to `chef-apply`.
SHACK-304
=> [SHACK-304] Promote chef-apply gem to Rubygems on every successful PR merge

.expeditor/config.yml
We will need to manually promote our gem to Rubygems. This is a partial revert of https://github.com/chef/chef-apply/pull/31
SHACK-304
=> [SHACK-304] Expeditor cannot auto-promote for us

Vagrantfile, lib/chef_apply/action/base.rb, lib/chef_apply/action/install_chef/base.rb, lib/chef_apply/minimum_chef_version.rb, spec/unit/action/base_spec.rb, spec/unit/action/install_chef/base_spec.rb, spec/unit/minimum_chef_version_spec.rb
Fixes https://github.com/chef/chef-apply/issues/22
Chef suffered from a variety of errors when trying to run with Tarball
support. On Windows the URI file unpacker fails with a GZip error. If we
specify relative paths on Chef 13 it thinks the files are at the root of
the directory.
We fix these by specifying full paths, and setting the minimum chef
versions to ones that include support for:
https://github.com/chef/chef/pull/7522
https://github.com/chef/chef/pull/7523
*NOTE*
Astute observers will notice that the minimum Chef 14 version on Windows (`14.4.22`) is not yet released. This is planned for next week. I did this because it kept the logic simpler and more straightforward. Otherwise I would have to make another PR next week to fix some complicated logic I added today. Windows is such …
=> [SHACK-290] Set minimum Chef 13 version to be 13.10.4 (fix policyfile tarball use on Windows)

i18n/errors/en.yml, lib/chef_apply/text.rb, lib/chef_apply/text/error_translation.rb, spec/unit/text/error_translation_spec.rb
This is the first part of decoupling error display/rendering options
from the code. This sets us up to move error display options to live
with the error definitions in i18n/errors/en.yml.
A new class ErrorTranslation encapsulates error messages translations,
providing access to both the text and the display attributes.
Note that this commit does not convert any messages or remove the
various convenience exceptions (such as ErrorNoLog) - that will follow
this work shortly.
This PR is one commit - once #16 merges, that'll be more clear.
=> [SHACK-187] capture error metadata in translations instead of code 

lib/chef_apply/action/converge_target.rb
Signed-off-by: Antoine Mazeas <antoine@karthanis.net>
In the converge step, `chef-apply` only outputs the received log from the target host with `Log.debug`. This is changed to `Log.info`.
As discussed in the related issue (#28), the target host's output is perhaps more important than `chef-apply`'s debug output, so this change reflects that. This also limits the noise around the target host's output.
This aims at resolving #28.
=> Changed log level requirement for target host output

i18n/errors/en.yml, lib/chef_apply/text.rb, lib/chef_apply/ui/error_printer.rb, spec/unit/ui/error_printer_spec.rb
Move error display attributes into translation yml
This is the first part of decoupling error display/rendering options
from the code. This sets us up to move error display options to live
with the error definitions in i18n/errors/en.yml.
A new class ErrorTranslation encapsulates error messages translations,
providing access to both the text and the display attributes.
Note that this commit does not convert any messages or remove the
various convenience exceptions (such as ErrorNoLog) - that will follow
this work shortly.
=> [SHACK-187] convert error handling to use new encapsulated display data

lib/chef_apply/target_host.rb
This change disables password prompts since they do not play nicely with
our current UX. A subsequent change may incorporate a custom prompt to
use instead.
This can merge at any time, but the options will not take effect until after https://github.com/inspec/train/pull/336 is merged.
=> [SHACK-271] Disable password prompts

lib/chef_apply/cli.rb, lib/chef_apply/config.rb, lib/chef_apply/ui/plain_text_element.rb, lib/chef_apply/ui/plain_text_header.rb, lib/chef_apply/ui/terminal.rb, lib/chef_apply/ui/terminal/job.rb, spec/unit/cli_spec.rb, spec/unit/ui/terminal_spec.rb
1) Pulled Job class out into its own file since we are referencing it more
2) Change dev spinner config value to true/false instead of specifying class names. This allow us to manage classes internally and developers only need to specify 'do I want spinners in my output or not'
3) Introduced a PlainTextHeader class. This allows us to turn the multi-spinner and regular spinner into just single line outputs so 'pry' starts working in local development again
N/A
Signed-off-by: tyler-ball <tball@chef.io>
=> Make pry breakpoints work with MultiSpinner

i18n/en.yml, lib/chef_apply/startup.rb, spec/unit/startup_spec.rb
chef-run is currently built as part of ChefDK for build dependency
reasons, however using it under DK is not supported.
When the chef-run command is run from within the ChefDK install,
we will now show an error directing the operator to download
Chef Workstation for access to chef-run.
=> [SHACK-359] Prevent chef-run from executing in the context of ChefDK.

lib/chef_apply/ui/terminal.rb, spec/unit/ui/terminal_spec.rb
When an error occurs during task execution in spinner, the cursor is not restored to visibility - even running `reset` on the terminal will not restore it. 
This commit ensures that we always restore cursor visibility even when failure occurs.
=> Ensure cursor is always restored to visible

lib/chef_apply/action/base.rb, lib/chef_apply/action/converge_target.rb, lib/chef_apply/action/install_chef/linux.rb, lib/chef_apply/target_host.rb, spec/unit/action/base_spec.rb, spec/unit/action/converge_target_spec.rb, spec/unit/target_host_spec.rb
This was added to work around permissions issues, where
a newly created directory would be created with sudo,
then upload over SCP would fail because it used the connecting user
who had no access to that directory.
Setting ownership is now encapsulated in TargetHost#mkdir and
TargetHost#mktemp, so that callers can mkdir then use it for upload
without worrying about platform-specific permissions behaviors.
This addresses https://github.com/chef/chef-apply/issues/40
=> Correct error 'bash: - invalid option'

lib/chef_apply/config.rb
If we do not do this the user could specify '~' in the path and we
try to interpret that as a real location
Reported in slack
=> Expand user supplied config paths

.expeditor/config.yml, .github/CODEOWNERS, .github/ISSUE_TEMPLATE/BUG_TEMPLATE.md, .github/ISSUE_TEMPLATE/DESIGN_PROPOSAL.md, .github/ISSUE_TEMPLATE/ENHANCEMENT_REQUEST_TEMPLATE.md, .github/ISSUE_TEMPLATE/SUPPORT_QUESTION.md, .github/PULL_REQUEST_TEMPLATE.md, .github/lock.yml, CHANGELOG.md
Auto assign the untriaged label on new issues
Add additional issue templates including the design proposal template
Add a codeowners file
Add a lock bot config
Remove default bits from the expeditor config and modernize the actions bit / label names
=> Add additional github templates and update the expeditor config

Gemfile.lock, chef-apply.gemspec, lib/chef_apply/action/generate_local_policy.rb, spec/unit/action/generate_local_policy_spec.rb, spec/unit/cli_spec.rb
=> Change over from ChefDK to ChefCLI 

lib/chef_apply/startup.rb, spec/unit/startup_spec.rb
We disable _writing_ telemetry data, but we should also disable sending.
N/A
=> Only send telemetry data if telemetry is enabled

lib/chef_apply/startup.rb, spec/unit/startup_spec.rb
I mistakenly thought that telemetry data would be sent even if telemetry
is disabled. But there is already a check in the `run` method of
sender.rb that prevents this. Reverting the above PR because it is
unnecessary and prevents cleaning up the telemetry data files (which
happens regardless of whether they are sent successfully).
Reverts https://github.com/chef/chef-apply/pull/96
=> Revert https://github.com/chef/chef-apply/pull/96

Gemfile.lock, chef-apply.gemspec
train 3.x conflicts (via train-winrm) with the rest of our Workstation
ecosystem, so need to pin below that for now.
=> Pinning Train to prevent pulling in train-winrm updates

Gemfile.lock, chef-apply.gemspec
`train-core` stays at 2.1.19 for now because that is a transitive dep of chef. Once we update chef to >= 15.3 `train-core` will update to >= 3.0. Since they are split out as `train` vs `train-core` there is no conflict, and `train-core` is just a subset of `train`.
N/A
=> We are updating to Train 3.x across the Workstation/DK, ensure this gets bumped

.expeditor/update_version.sh
Since we removed the `Gemfile.lock` we no longer need to run a bundle
update on version bumps.
Signed-off-by: Salim Afiune <afiune@chef.io>
N/A
=> Avoid running bundle update on version bump

.expeditor/run_linux_tests.sh, chef-apply.gemspec
Also use the new test script better caches the gems during the run.
Remove the specs and the readme from the gem artifact to reduce the size
of the install artifact. This drops our Workstation install size by 51
files and 238k on disk.
I changed the train dep from train to train-core since we also dep on
chef 15+ which includes train-core as a dep. There's no reason to
install both versions of train in CI for testing. In the workstation
package we'll end up installing both, but this is *more* correct. We
don't need all the azure/gce/ec2 deps just to test chef-apply since it
doesn't use any of that.
=> Slim the gem down by removing specs + switch from train to train-core

chef-apply.gemspec, lib/chef_apply/config.rb
Strict mode was originally enabled to provide a better UX
around validated configuration entries, but the scope of chef-workstation
configuration has expanded beyond this single tool.
Disabling this allows us to avoid adding config support to chef-apply
every time we add new config keys for chef workstation app,
chef command line, chef-analyze, etc.  
The trade-off is that
we will not be able to detect when the operator has a bad configuration
that includes keys that are genuinely invalid.
=> Disable strict config checking

chef-apply.gemspec
This prevents us from pulling a refactor which folds
in many of the bits from chef-core/chef-apply (Telemeter, etc).
We'll need some changes on this side before we can take that in.
=> Pin chef-telemetry to 1.0.10

i18n/errors/en.yml, lib/chef_apply/cli/options.rb, lib/chef_apply/telemeter.rb, spec/unit/cli_spec.rb
Fixes #118
This also corrects an error introduced with the shift to the new telemetry library, where our error handling would cause a call to ChefApply::Telemeter::capture, which does not exist. 
Finally, it changes CHEFVAL001 (unreadable key) behavior so that it does not try to print usgae - showing usage when we already have a clear error and path for the operator to correct it just muddies the output. 
=> Add missing error CHEFVAL001

.expeditor/verify.pipeline.yml, i18n/en.yml, lib/chef_apply/config.rb, lib/chef_apply/startup.rb, spec/unit/action/install_chef_spec.rb
Also adds testing for Ruby 2.7 since Workstation is releasing with that
soon and fixes a warning discovered in 2.7.
=> Fix some mismatches in config values we send to the telemetry gem

lib/chef_apply/cli/validation.rb, spec/unit/cli/validation_spec.rb
=> Allow passing symbols for ad-hoc resource property values 

bin/chef-run, lib/chef_apply/cli.rb, lib/chef_apply/startup.rb, spec/integration/spec_helper.rb, spec/unit/cli_spec.rb
This implements a similar feature that other check binaries have such as
chef-client to use a parameter in the CLI startup to toggle license enforcement.
This is useful for other Chef distributions (such as Cinc) to more easily allow
running this without verifying the license with minimal patching.
Signed-off-by: Lance Albertson <lance@osuosl.org>
I'm not thrilled with how I implemented this since I had to follow down the chain of various methods. I feel like there is a better way to do this, so please let me know.
=> Add enforce_license license parameter to cli startup

i18n/en.yml, i18n/errors/en.yml, spec/integration/fixtures/chef_help.out
Capitalize the tool name and use the full marketing name
=> Update all references to Chef to be Chef Infra

Vagrantfile, lib/chef_apply/action/install_chef.rb, lib/chef_apply/action/install_chef/minimum_chef_version.rb, lib/chef_apply/cli.rb, lib/chef_apply/target_host.rb, lib/chef_apply/target_host/solaris.rb, lib/chef_apply/ui/terminal.rb, spec/unit/target_host/solaris_spec.rb
Allows Solaris hosts as a target for chef-apply 
https://github.com/chef/chef-apply/issues/156
=> Set solaris as target in chef-apply

cspell.json, lib/chef_apply/action/install_chef.rb, lib/chef_apply/target_host.rb, lib/chef_apply/target_host/aix.rb, spec/unit/target_host/aix_spec.rb
Adding 'aix' as a supported target operating system.
solves https://github.com/chef/chef-apply/issues/38
=> Support AIX for chef adhoc runs
